### ISSUE TITLE
Esta um nome repetido no README

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/github-workshop#27]
## Description

"margarida melo" esta repetido

## Acceptance Criteria

* Alguem pode remover?

**Comment by PMLF** [comment]
Temos "Margarida Melo", "Isabel Costa" e "Joana Santos" repetidos.
A Joana está uma vez como "Joana C Santos" que foi ela que adicionou (e bem) e o "Joana Santos" sem o "C" fomos nós para exemplificar, mas pode-se remover agora.
Alguém corajoso para resolver isto?
@joanacsantos @1181092 @anyone

**Comment by margmelo** [comment]
Okay vou ver disso agora

**Comment by margmelo** [comment]
#29 done

**Comment by PMLF** [comment]
Resolvido com o PR #29 da @1181092 👆
